Use klog instead of glog
Previously we got logging like ...
ERROR: logging before flag.Parse: I0213 09:49:05.242462   20171 server.go:70] Run GNMI Server...

Add workaround copied from onos-config - https://github.com/onosproject/onos-config/pull/398